apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: assignment-role
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "persistentvolumeclaims", "secrets"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "watch", "list", "create", "delete"]
